[package]
name = "panamax"
version = "0.1.0"
authors = ["k3d3 <k@3d3.ca>"]
description = "Mirror rustup and crates.io repositories, for offline or airgapped Rust and cargo usage."
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/k3d3/panamax"
repository = "https://github.com/k3d3/panamax"
edition = "2018"

[dependencies]
reqwest = "0.9.18"
indicatif = "0.11.0"
structopt = "0.2.18"
toml = "0.5.1"
serde_derive = "1.0.94"
serde = "1.0.94"
quick-error = { package = "quick-error2", version = "2.0.1" }
console = "0.7.7"
